### PR TITLE
Add an OrganSegmentation task

### PR DESCRIPTION
**Pull request by jlegrand62**
It uses a DBSCAN clustering method on the segmented point cloud to detect organs.

### CODE REVIEW

**Comment by jlegrand62** [comment]
Can be tested with:
```bash
romi_run_task OrganSegmentation database_jcharlaix/scans_reconstructed/arabido_test2_ml/ --config configs/ml_pipe_vplants_4.toml
```

**Comment by jlegrand62** [comment]
Example of clustering on PEDICEL (left) & FRUIT (right):
Capture d’écran de 2020-11-18 19-32-39

**Comment by fabfabBesnard** [comment]
For clarity, I prefer adding some information (correct me if I am wrong):

- the **input** of new task `OrganSegmentation` is a _labelled_ point cloud, where labels were given by deep learning from 2D images (ml pipeline only)

- the **output** is still a point cloud, but this time neighboring points with the same label are clustered in a unique object with a class, providing an instance segmentation of the point cloud. The class is derived from the classes of the point labels, on which the machine learning phase was trained initially (namely: stem, leaf, flower, fruit, pedicle)

- the output is stored in a dedicated folder, whose name starts looks like "OrganSegmentation_2_0_5_out_8a261572f8"

- In the [ml pipe]( https://docs.romi-project.eu/Scanner/user_guide/pipelines/), this task replaces ClusteredMesh and connects directly `SegmentedPointCloud` to `AnglesAndInternodes`

**Review by fabfabBesnard — APPROVED** [review]
-PR tested 24/11/2020 on AWS
-docker image build on AWS (Repository /Tag/Image ID: `romiscan                           PR139_Organ_segmentation   9ac1e990867d`)
-tested scan: **db_eval_1/2018-11-27_11-24-05** (acquired long time ago on old plant culture scanner)
-results inspected on my PC with Jupyter notebook (this notebook works well to check results). Instance clusters were present for leaves, flowers, fruits
-piping `AnglesAndInternodes` task after `OrganSegmentation` task works well on my PC an results can be nicely displayed on the 3d plant Viewer

Next, I will try to run the entire ml pipe from start up to `AnglesAndInternodes` (replacing ClusteredMesh by OrganSegmentation) on the whole db_eval_1. But I think we can consider now that this PR works and can be merged.

**Comment by fabfabBesnard** [comment]
Note before merging:
edit the romiscan/config/ml_pipe_full.toml with new task

**Comment by jlegrand62** [comment]
> Note before merging:
> edit the romiscan/config/ml_pipe_full.toml with new task

Maybe I should wait to test `OrganSegmentation` for repeatability against `ClusteredMesh` and prove its more robust?!

**Comment by jlegrand62** [comment]
I have this `robustness_comparison` script ready in a branch that should be quickly mergeable with this one!

**Review by jcharlaix — APPROVED** [review]

**Pull request merged**
