### PR TITLE
Build docker from local sources

### LINKED ISSUE #157: Use COPY in Dockerfile instead of "git clone && ..." and update the doc
Avoid cloning the repo from github and use instead local files -> better for debugging and prevent using abusive CI

### PR DESCRIPTION
**Pull request by naittaleb**
close #157 

These PR includes:
- The Dockerfile uses COPY to use the local source files instead of passing a branch name as a parameter
- A minimal documentation on how to build and run the docker image
- Add a text editor in the docker image to facilitate debugging

### CODE REVIEW

**Comment by jlegrand62** [comment]
I am ok with the changes.

I see two changes on stuff I did to ease the work of "biologist", so I will let them argue if they still need it:
1.  you removed (again) the `dev` approach that speeds up the test of the docker build by creating a base image (useful for debug)
2. you did not copy/transpose the 'git update' mechanism (`run.sh`) and we will have to rebuild the image from scratch every time (or hope that the docker build cache will save time for us)

**Comment by jlegrand62** [comment]
By what mechanism the CI server has up-to-date local copies of each required repo and know the branches to use in the build ?!

**Comment by naittaleb** [comment]
> By what mechanism the CI server has up-to-date local copies of each required repo and know the branches to use in the build ?!

For each pull_request, an action checkout is performed and the right branch is synchronized.

**Comment by naittaleb** [comment]
> I am ok with the changes.
> 
> I see two changes on stuff I did to ease the work of "biologist", so I will let them argue if they still need it:
> 
> 1. you removed (again) the `dev` approach that speeds up the test of the docker build by creating a base image (useful for debug)
> 2. you did not copy/transpose the 'git update' mechanism (`run.sh`) and we will have to rebuild the image from scratch every time (or hope that the docker build cache will save time for us)

As discussed during the meeting a cache mechanism could speed up the docker build and a nightly build will be performed every time new commits are pulled from `dev`

**Pull request merged**
