### PR TITLE
Feature/test pipe

### LINKED ISSUE #150: Better test scripts (with options)
The pipeline 'test scripts' should have options & allows to execute it in a temporary directory to avoid messing up the `testdata` folder since the `Clean` task is not reliable!

### PR DESCRIPTION
**Pull request by jlegrand62**
Close #150 

Notes that as of now, the pipeline is not tested on the virtual plant anymore (anyway it fails according to @naittaleb).

### CODE REVIEW

**Comment by fabfabBesnard** [comment]
**Suggestion for improve**: ensure that 'check_pipe.sh' store and keep the results of a scan for the two pipes (ml and geom) instead of overwriting.

**Comment by naittaleb** [comment]
Could you please explain a little bit more about the goal of this task @jlegrand62 and @fabfabBesnard ?

How about fixing the `Clean` command since it seems to be the root problem?

**Review by naittaleb — COMMENTED** [review]
My remarks are in the Conversation section. please refer to that.

**Comment by jlegrand62** [comment]
The starting point was indeed to overcome the troubles with the Clean task. However it escalated quickly to adding more options to also use the files check*_pipe.py for local testing purposes rather than only for CI test operations...

So now you can quickly test changes locally by using `check*_pipe.py --tmp`.
I admit that it may look redundant with the previous work we did with `romi_run_task.py`.
But notes that there are other options that also helps to test a specific task (other than `AnglesAndInternodes`) and dataset (other than the real or virtual plant).

Also, since we might evolve to a new data model, the Clean task will become obsolete... So I preferred not to waste time on it.
However if we want to keep the original romidb implementation 'alive', we will have to correct the Clean task!

**Comment by jlegrand62** [comment]
> **Suggestion for improve**: ensure that 'check_pipe.sh' store and keep the results of a scan for the two pipes (ml and geom) instead of overwriting.

If you use the `--tmp` option, it will create a dataset name with a `$date_$time_$dataset` format like:
```
2021-01-27_11-48-15_GEOM_real_plant
2021-01-27_11-50-48_ML_real_plant
```

**Pull request merged**
